In [3]:
import tensorflow as tf
print("TensorFlow version: ", tf.__version__)

TensorFlow version:  2.15.0


In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test,y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.24760404,  0.34048346,  0.6072457 ,  0.76097935,  0.16455168,
        -0.4747942 ,  0.34236968, -0.22590706,  0.38960418,  0.26897585]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.06026467, 0.10850906, 0.14168352, 0.16522852, 0.09100384,
        0.04801704, 0.10871392, 0.06158653, 0.11397217, 0.10102075]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

3.0361996

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2980 - accuracy: 0.9126
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1410 - accuracy: 0.9582
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1072 - accuracy: 0.9671
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0857 - accuracy: 0.9732
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0764 - accuracy: 0.9765


In [13]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0750 - accuracy: 0.9776 - 629ms/epoch - 2ms/step


[0.07502833753824234, 0.9775999784469604]

In [14]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.8440135e-08, 3.1537299e-09, 1.3974702e-06, 3.0635350e-05,
        2.9228896e-12, 4.1473765e-08, 7.2091720e-14, 9.9996412e-01,
        5.0991787e-07, 3.3436975e-06],
       [4.7923416e-09, 3.4246530e-06, 9.9996698e-01, 2.3418661e-05,
        2.2692952e-18, 2.1922470e-07, 7.5889410e-09, 3.7422951e-16,
        5.9933218e-06, 9.5736631e-14],
       [2.4585617e-07, 9.9812406e-01, 3.2678104e-04, 3.3401288e-05,
        6.7983623e-05, 4.2547099e-06, 5.9443437e-06, 9.1779727e-04,
        5.1810913e-04, 1.3385562e-06],
       [9.9883455e-01, 2.3018681e-10, 1.0416763e-03, 3.0805371e-08,
        1.2688072e-06, 5.1061465e-07, 1.5084430e-05, 6.5433642e-06,
        3.8420933e-07, 9.9862868e-05],
       [4.1615337e-07, 8.8923597e-09, 4.4726946e-07, 3.1486373e-08,
        9.9908984e-01, 3.0307824e-08, 4.1506220e-07, 6.3323845e-05,
        3.8472666e-07, 8.4525737e-04]], dtype=float32)>